steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-docker-image', '.']

  # Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-docker-image']

  # Deploy the Docker image to a GCE instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'update-container'
      - 'my-instance-name'  # Replace with your GCE instance name
      - '--zone=us-central1-a'  # Replace with your GCE instance zone
      - '--container-image=gcr.io/$PROJECT_ID/my-docker-image'
