steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-docker-image', '.']

  # Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-docker-image']

  # Deploy the Docker image to a GCE instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'instance-1'  # Replace with your GCE instance name
      - '--zone=us-central1-a'  # Replace with your GCE instance zone
      - '--command=docker pull gcr.io/$PROJECT_ID/my-docker-image && docker run -d -p 80:80 gcr.io/$PROJECT_ID/my-docker-image'

