steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/YOUR_IMAGE_NAME:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/YOUR_IMAGE_NAME:$COMMIT_SHA']
# Deploy the Docker image to a GCE instance
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'instances'
  - 'update-container'
  - 'instance-1'  # Replace with your GCE instance name
  - '--zone=YOUR_ZONE'  # Replace with your GCE instance zone
  - '--container-image=gcr.io/$PROJECT_ID/YOUR_IMAGE_NAME:$COMMIT_SHA'
  - '--project=YOUR_PROJECT_ID'  # Replace with your GCP project ID
  - '--quiet'
