steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/friendly-folio-408616/YOUR_IMAGE_NAME:latest', '.']

# Push the Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/friendly-folio-408616/YOUR_IMAGE_NAME:latest']

# Deploy the Docker image to a GCE instance
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'instances'
  - 'update-container'
  - 'instance-1'  # Replace with your GCE instance name
  - '--zone=us-central1'  # Replace with your GCE instance zone
  - '--container-image=gcr.io/friendly-folio-408616/YOUR_IMAGE_NAME:latest'
  - '--project=friendly-folio-408616'  # Replace with your GCP project ID
  - '--quiet'
